### ISSUE TITLE
QR code not showing up

### ISSUE THREAD

**Issue by Skeetastic** [DismissedGuy/Discord-QR-Auth-Client#4]
Using kali linux and the qr code doesn't pop up.
How do I get the qr code?

**Comment by malmeloo** [comment]
Hi,

The program uses PIL's `Image.show()` to display the QR code. You should make sure that you have an image viewer installed on your system. For Linux, I can confirm imagemagick is working, so maybe give that a try.

Closing because this is not a bug in my program.
